name: main (CI)
on:
  pull_request:
    branches:
      - main

jobs:
#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.head_ref }}
#
#      - name: Set up Go environment
#        uses: actions/setup-go@v3
#        with:
#          go-version: '1.24'
#
#      - name: Install Go dependencies
#        run: go mod tidy
#
#      - name: Run linters
#        uses: golangci/golangci-lint-action@v4

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./... -v --race

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}